[package]
name = "s"
version = "0.1.0"
edition = "2018"

[dependencies]
sparser = { path = "./sparser" }
scalcurator = { path = "./scalcurator" }


[workspace]
members =  [
    "sparser",
    "scalcurator",
]
